### ISSUE TITLE
cubit2specfem2d.py "mesh" is not defined!

### ISSUE THREAD

**Issue by AbolfazlKhanMo** [SPECFEM/specfem2d#1168]
Hi all,

I was using specfem2d on my previous OS (**Ubuntu 20.04**). After upgrading to **Ubuntu 22.4**, when I run the "cubit2specfem2d.py" script to get the necessary files in specfem2d format, I get the following error:

_(Non-Commercial License) Cubit>
Traceback (most recent call last):
  File "<string>", line 750, in <module>
  File "<string>", line 3, in export2SPECFEM2D
NameError: name 'mesh' is not defined_

Rolled back to the previous os version, and I am still getting the same error.
Thank you!

**Comment by AbolfazlKhanMo** [comment]
I'm going to close this because I solved it. But I only ran a homogeneous media and the "paper_axisymmetry_example"  simulations using Cubit! They both work fine.

Solution steps:
(1) you don't need the "sets" module for calling the "set" function in python anymore. Make all the _from sets import Set_  comment. 
(2) Also, in line 257 of the script, switch the"mesh_tools" and "object". So, it should be _class mesh(mesh_tools,object):_
